# -*- coding: utf-8 -*-
"""uas_praktikum_G.231.21.0138.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FrTAY6kdt2u_mKw96gkmmMCYviQvKLo7
"""

import pandas as pd
import matplotlib.pyplot as plt
dataset = pd.read_csv ('stock.csv')
dataset.head(14)

import matplotlib.pyplot as plt
plt.figure(figsize=(10,5))
plt.hist(dataset['Purchase Price'], bins=50, color='orange', edgecolor='red')
plt.xlabel('Purchase Price')
plt.ylabel('Distribusi')
plt.title('Histogram of Purchase Price')

plt.show()

import matplotlib.pyplot as plt
plt.figure(figsize=(10,5))
plt.hist(dataset['Current Price'], bins=100, color='green', edgecolor='black')
plt.xlabel('Current Price')
plt.ylabel('Distribusi')
plt.title('Histogram of Current Price')

plt.show()

import matplotlib.pyplot as plt
plt.figure(figsize=(10,5))
plt.hist(dataset['Current Price'], bins=80, color='blue', edgecolor='navy')
plt.xlabel('Gain/Loss')
plt.ylabel('Distibusi')
plt.title('Histogram of Gain/Loss')
plt.show()

Dividend_top5 = dataset.nlargest(5, 'Dividend/share')[['Stock Name', 'Symbol', 'Dividend/share']]
print('Stock Name dan Symbol yang memiliki Dividen / Share 5 tertinggi:')
print(' ')
print(Dividend_top5)



top_market_value = dataset.nlargest(5, 'Market Value')[['Stock Name', 'Symbol', 'Market Value']]
print('Atribut Stock Name dan Symbol yang memiliki Market Value 5 tertinggi:')
print(top_market_value)

annual_yield_7tertinggi = dataset.nlargest(7, 'Annual Yield')[['Stock Name', 'Symbol', 'Annual Yield']]
print('Atribut Stock Name dan Symbol yang memiliki Annual Yield 7 tertinggi:')
print(' ')
print(annual_yield_7tertinggi)